cc_test(
    name = "merge_sorted_array",
    srcs = ["q88.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "remove_element",
    srcs = ["q27.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "remove_duplicates_from_sorted_array",
    srcs = ["q26.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "remove_duplicates_from_sorted_array_ii",
    srcs = ["q80.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "majority_element",
    srcs = ["q169.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "rotate_array",
    srcs = ["q189.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)