cc_test(
    name = "merge_sorted_array",
    srcs = ["q88.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "remove_element",
    srcs = ["q27.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "remove_duplicates_from_sorted_array",
    srcs = ["q26.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "remove_duplicates_from_sorted_array_ii",
    srcs = ["q80.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "majority_element",
    srcs = ["q169.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "rotate_array",
    srcs = ["q189.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "best_time_to_buy_and_sell_stock",
    srcs = ["q121.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "best_time_to_buy_and_sell_stock_ii",
    srcs = ["q122.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "best_time_to_buy_and_sell_stock_iii",
    srcs = ["q123.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "jump_game",
    srcs = ["q55.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "jump_game_ii",
    srcs = ["q45.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "insert_delete_getrandom_o1",
    srcs = ["q380.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "product_of_array_except_self",
    srcs = ["q238.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "gas_station",
    srcs = ["q134.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "candy",
    srcs = ["q135.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "trapping_rain_water",
    srcs = ["q42.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "roman_to_integer",
    srcs = ["q13.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "integer_to_roman",
    srcs = ["q12.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "longest_common_prefix",
    srcs = ["q14.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)