cc_test(
    name = "merge_sorted_array",
    srcs = ["q88.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "remove_element",
    srcs = ["q27.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "remove_duplicates_from_sorted_array",
    srcs = ["q26.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "remove_duplicates_from_sorted_array_ii",
    srcs = ["q80.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "majority_element",
    srcs = ["q169.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "rotate_array",
    srcs = ["q189.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "best_time_to_buy_and_sell_stock",
    srcs = ["q121.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "best_time_to_buy_and_sell_stock_ii",
    srcs = ["q122.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "best_time_to_buy_and_sell_stock_iii",
    srcs = ["q123.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "jump_game",
    srcs = ["q55.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "jump_game_ii",
    srcs = ["q45.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "insert_delete_getrandom_o1",
    srcs = ["q380.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "product_of_array_except_self",
    srcs = ["q238.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "gas_station",
    srcs = ["q134.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "candy",
    srcs = ["q135.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "trapping_rain_water",
    srcs = ["q42.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "roman_to_integer",
    srcs = ["q13.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "integer_to_roman",
    srcs = ["q12.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "longest_common_prefix",
    srcs = ["q14.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "reverse_words_in_a_string",
    srcs = ["q151.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "zigzag_conversion",
    srcs = ["q6.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "find_index_of_first_occurence_of_string",
    srcs = ["q28.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(                                                                 
    name = "valid_palindrome",
    srcs = ["q125.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(                                                                 
    name = "palindrome_linked_list",
    srcs = ["q234.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(                                                                 
    name = "is_subsequence",
    srcs = ["q392.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(                                                                 
    name = "two_sum",
    srcs = ["q1.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "two_sum_input_array_sorted",
    srcs = ["q167.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "container_with_most_water",
    srcs = ["q11.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "three_sum",
    srcs = ["q15.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "minimum_size_subarray_sum",
    srcs = ["q209.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "longest_substring_without_repeating_characters",
    srcs = ["q3.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "substring_with_concatenation_of_all_words",
    srcs = ["q30.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "permutations",
    srcs = ["q46.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "combinations",
    srcs = ["q77.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "minimum_window_substring",
    srcs = ["q76.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "valid_sudoku",
    srcs = ["q36.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "spiral_matrix",
    srcs = ["q54.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "rotate_matrix",
    srcs = ["q48.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "ransom_note",
    srcs = ["q383.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)

cc_test(
    name = "isomorphic_strings",
    srcs = ["q205.cpp"],
    deps = [
        "@com_google_googletest//:gtest_main",
        "@glog",
    ],
)